name: app_cecyt
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  page_transition: ^2.0.4
  cupertino_icons: ^1.0.6
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  bloc: ^8.1.4
  meta: ^1.12.0
  intl: ^0.19.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.2
  flutter_svg: ^2.0.10  

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_animate: ^4.5.0

flutter_launcher_icons:
  android: true
  image_path: "assets/cecytLogo.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true

  assets:
    - assets/cecytlogo.png
    - assets/Informacion.png
    - assets/InformacionFoto1.png
    - assets/InformacionFoto2.png
    - assets/Innotec.png
    - assets/Organizadores.png
    - assets/innotec_logo.png
    - assets/Preguntas.png
    - assets/hackatonImage2.jpg
    - assets/hackatonimage3.jpg
    - assets/Innotec_Charla2.jpg
    - assets/innotec_charla3.jpg
    - assets/innotec_charla4.jpg
    - assets/hackatonimage5.png
    - assets/dotImage.jpeg
    - assets/dotAd.png
    - assets/InfoDot.png
    - assets/PreguntasDot.png
    - assets/FechaDot.png
    - assets/cecytLogo.png
    - assets/DotGroup.png
    - assets/dotinfoFoto.jpeg
    - assets/dotinfo2.jpeg
    - assets/CECYT_Fondo_Claro.jpg
    - assets/Recurso 6.png
    - assets/Recurso 7.png
    - assets/logoInnotec_lindo.jpg
    - assets/Hora.svg
    - assets/Fecha.svg
    - assets/Ubicacion.svg
    - assets/LogoCyT.jpg
    - assets/Ejemplo_Foto_Perfil.jpg
    - assets/Recurso 8.png
    
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-LightItalic.ttf
          weight: 300
